version: '3.8'
services:
  db:
    image: redis:7.0-alpine
    restart: always
    env_file:
      - .env
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes: 
      - hackers_cache:/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - db
volumes:
  hackers_cache: