version: '3.8'
services:
  db:
    image: redis:7.0-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes: 
      - hackers_cache:/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8010:8010"
    depends_on:
      - db
volumes:
  hackers_cache: